plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.guard'
    compileSdk 35

    defaultConfig {
        applicationId "com.example.guard"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file('../guard.keystore')
            storePassword 'android'
            keyAlias 'guard'
            keyPassword 'android'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
}
